spring.application.name=ExpanseTrackerAPI
spring.datasource.url=jdbc:mysql://localhost:3306/exp_track
spring.datasource.username=root
spring.datasource.password=Gojo@2003
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
